"use client";

import { useState } from "react";
import { SerializedEditorState } from "lexical";

import { Editor } from "@/components/blocks/editor-x/editor";
import { ChevronLeft } from "lucide-react";
import {
   Sheet,
   SheetClose,
   SheetContent,
   SheetDescription,
   SheetFooter,
   SheetHeader,
   SheetTitle,
   SheetTrigger,
} from "@/components/ui/sheet";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Tag, TagInput } from "emblor";

export const initialValue = {
   root: {
      children: [
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "h1",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "heading",
            version: 1,
            tag: "h1",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "h2",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "heading",
            version: 1,
            tag: "h2",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "h3",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "heading",
            version: 1,
            tag: "h3",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "h4",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "heading",
            version: 1,
            tag: "h4",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "h5",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "heading",
            version: 1,
            tag: "h5",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "h6",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "heading",
            version: 1,
            tag: "h6",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 1,
                  mode: "normal",
                  style: "",
                  text: "bold",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 1,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 2,
                  mode: "normal",
                  style: "",
                  text: "italic",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 2,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 8,
                  mode: "normal",
                  style: "",
                  text: "underline",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 8,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 4,
                  mode: "normal",
                  style: "",
                  text: "strikethrough",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 4,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 16,
                  mode: "normal",
                  style: "",
                  text: "code",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 16,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "subscript",
                  type: "text",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 32,
                  mode: "normal",
                  style: "",
                  text: "sub",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 0,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "superscript",
                  type: "text",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 64,
                  mode: "normal",
                  style: "",
                  text: "super",
                  type: "text",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 0,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 128,
                  mode: "normal",
                  style: "",
                  text: "Important!",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 128,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 3,
                  mode: "normal",
                  style: "",
                  text: "italic + bold",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 3,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 11,
                  mode: "normal",
                  style: "",
                  text: "italic + bold + underline",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 11,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 15,
                  mode: "normal",
                  style: "",
                  text: "italic + bold + underline + strikethrough",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 15,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 31,
                  mode: "normal",
                  style: "",
                  text: "italic + bold + underline + strikethrough + code",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 31,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "This is a numbered list:",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 0,
            textStyle: "",
         },
         {
            children: [
               {
                  children: [
                     {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "item1",
                        type: "text",
                        version: 1,
                     },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "listitem",
                  version: 1,
                  value: 1,
               },
               {
                  children: [
                     {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "item2",
                        type: "text",
                        version: 1,
                     },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "listitem",
                  version: 1,
                  value: 2,
               },
               {
                  children: [
                     {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "item3",
                        type: "text",
                        version: 1,
                     },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "listitem",
                  version: 1,
                  value: 3,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "list",
            version: 1,
            listType: "number",
            start: 1,
            tag: "ol",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "This is a bullet list:",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 0,
            textStyle: "",
         },
         {
            children: [
               {
                  children: [
                     {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "item1",
                        type: "text",
                        version: 1,
                     },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "listitem",
                  version: 1,
                  value: 1,
               },
               {
                  children: [
                     {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "item2",
                        type: "text",
                        version: 1,
                     },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "listitem",
                  version: 1,
                  value: 2,
               },
               {
                  children: [
                     {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "item3",
                        type: "text",
                        version: 1,
                     },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "listitem",
                  version: 1,
                  value: 3,
               },
               {
                  children: [
                     {
                        children: [
                           {
                              children: [
                                 {
                                    detail: 0,
                                    format: 0,
                                    mode: "normal",
                                    style: "",
                                    text: "sdvsdv",
                                    type: "text",
                                    version: 1,
                                 },
                              ],
                              direction: "ltr",
                              format: "",
                              indent: 1,
                              type: "listitem",
                              version: 1,
                              value: 1,
                           },
                           {
                              children: [
                                 {
                                    children: [
                                       {
                                          children: [
                                             {
                                                detail: 0,
                                                format: 0,
                                                mode: "normal",
                                                style: "",
                                                text: "vdfbdsfbdb",
                                                type: "text",
                                                version: 1,
                                             },
                                          ],
                                          direction: "ltr",
                                          format: "",
                                          indent: 2,
                                          type: "listitem",
                                          version: 1,
                                          value: 1,
                                       },
                                    ],
                                    direction: "ltr",
                                    format: "",
                                    indent: 0,
                                    type: "list",
                                    version: 1,
                                    listType: "bullet",
                                    start: 1,
                                    tag: "ul",
                                 },
                              ],
                              direction: "ltr",
                              format: "",
                              indent: 1,
                              type: "listitem",
                              version: 1,
                              value: 2,
                           },
                        ],
                        direction: "ltr",
                        format: "",
                        indent: 0,
                        type: "list",
                        version: 1,
                        listType: "bullet",
                        start: 1,
                        tag: "ul",
                     },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "listitem",
                  version: 1,
                  value: 4,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "list",
            version: 1,
            listType: "bullet",
            start: 1,
            tag: "ul",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "#tag",
                  type: "hashtag",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "text",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "#tag2",
                  type: "hashtag",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "text",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "#tag3",
                  type: "hashtag",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 0,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "This is a checklist:",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 0,
            textStyle: "",
         },
         {
            children: [
               {
                  children: [
                     {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "item1",
                        type: "text",
                        version: 1,
                     },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "listitem",
                  version: 1,
                  checked: false,
                  value: 1,
               },
               {
                  children: [
                     {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "item2",
                        type: "text",
                        version: 1,
                     },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "listitem",
                  version: 1,
                  checked: true,
                  value: 2,
               },
               {
                  children: [
                     {
                        children: [
                           {
                              children: [
                                 {
                                    detail: 0,
                                    format: 0,
                                    mode: "normal",
                                    style: "",
                                    text: "item3",
                                    type: "text",
                                    version: 1,
                                 },
                              ],
                              direction: "ltr",
                              format: "",
                              indent: 1,
                              type: "listitem",
                              version: 1,
                              checked: false,
                              value: 1,
                           },
                           {
                              children: [
                                 {
                                    detail: 0,
                                    format: 0,
                                    mode: "normal",
                                    style: "",
                                    text: "item4",
                                    type: "text",
                                    version: 1,
                                 },
                              ],
                              direction: "ltr",
                              format: "",
                              indent: 1,
                              type: "listitem",
                              version: 1,
                              checked: true,
                              value: 2,
                           },
                        ],
                        direction: "ltr",
                        format: "",
                        indent: 0,
                        type: "list",
                        version: 1,
                        listType: "check",
                        start: 1,
                        tag: "ul",
                     },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "listitem",
                  version: 1,
                  checked: false,
                  value: 3,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "list",
            version: 1,
            listType: "check",
            start: 1,
            tag: "ul",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "This is a codeblock:",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 0,
            textStyle: "",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "import",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "{",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " dirname ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "}",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "from",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: '"path"',
                  type: "code-highlight",
                  version: 1,
                  highlightType: "string",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ";",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "import",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "{",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " fileURLToPath ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "}",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "from",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: '"url"',
                  type: "code-highlight",
                  version: 1,
                  highlightType: "string",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ";",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "import",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "{",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " FlatCompat ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "}",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "from",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: '"@eslint/eslintrc"',
                  type: "code-highlight",
                  version: 1,
                  highlightType: "string",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ";",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "const",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " __filename ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "=",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "operator",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "fileURLToPath",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "function",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "(",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "import",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ".",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "meta",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ".",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "url",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ")",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ";",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "const",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " __dirname ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "=",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "operator",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "dirname",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "function",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "(",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "__filename",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ")",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ";",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "const",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " compat ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "=",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "operator",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "new",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "FlatCompat",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "class-name",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "(",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "{",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "  ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "baseDirectory",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "literal-property",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ":",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "operator",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " __dirname",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ",",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "}",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ")",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ";",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "const",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " eslintConfig ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "=",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "operator",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "[",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "  ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "...",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "operator",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "compat",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ".",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "extends",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "function",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "(",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: '"next/core-web-vitals"',
                  type: "code-highlight",
                  version: 1,
                  highlightType: "string",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ",",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: '"next/typescript"',
                  type: "code-highlight",
                  version: 1,
                  highlightType: "string",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ")",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ",",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "]",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ";",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  type: "linebreak",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "export",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "default",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "keyword",
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " eslintConfig",
                  type: "code-highlight",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: ";",
                  type: "code-highlight",
                  version: 1,
                  highlightType: "punctuation",
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "code",
            version: 1,
            language: "js",
         },
         {
            children: [
               {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "This is a ",
                  type: "text",
                  version: 1,
               },
               {
                  detail: 0,
                  format: 1,
                  mode: "normal",
                  style: "",
                  text: "quote",
                  type: "text",
                  version: 1,
               },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "quote",
            version: 1,
         },
         {
            children: [],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 0,
            textStyle: "",
         },
         {
            type: "horizontalrule",
            version: 1,
         },
         {
            children: [],
            direction: null,
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 0,
            textStyle: "",
         },
         {
            children: [],
            direction: null,
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
            textFormat: 0,
            textStyle: "",
         },
      ],
      direction: "ltr",
      format: "",
      indent: 0,
      type: "root",
      version: 1,
      textStyle: "background-color: #faf006;",
   },
} as unknown as SerializedEditorState;

export default function EditorPage() {
   const [editorState, setEditorState] =
      useState<SerializedEditorState>(initialValue);
   console.log(editorState);
   const [tags, setTags] = useState<Tag[]>([]);
   const [activeTagIndex, setActiveTagIndex] = useState<number | null>(null);
   return (
      <div className="relative w-full overflow-hidden">
         <Editor
            editorSerializedState={editorState}
            onSerializedChange={(value) => setEditorState(value)}
         />
         <Sheet>
            <SheetTrigger asChild>
               <div className="bg-background p-2 flex items-center justify-center absolute top-24 right-0 w-12 h-12 rounded-l-full border border-r-0">
                  <ChevronLeft />
               </div>
            </SheetTrigger>
            <SheetContent>
               <SheetHeader>
                  <SheetTitle>Edit meta-data</SheetTitle>
                  <SheetDescription>
                     Make changes to the meta data of the blog here. Click save
                     when you&apos;re done.
                  </SheetDescription>
               </SheetHeader>
               <div className="grid flex-1 auto-rows-min gap-6 px-4">
                  <div className="grid gap-3">
                     <Label htmlFor="sheet-demo-name">Title</Label>
                     <Input id="sheet-demo-name" defaultValue="Pedro Duarte" />
                  </div>
                  <div className="grid gap-3">
                     <Label htmlFor="sheet-demo-name">Tags</Label>
                     <TagInput
                        placeholder="Enter a topic"
                        tags={tags}
                        setTags={(newTags) => {
                           setTags(newTags);
                        }}
                        activeTagIndex={activeTagIndex}
                        setActiveTagIndex={setActiveTagIndex}
                        styleClasses={{
                           input: "focus:outline-none px-1 shadow-none",
                           inlineTagsContainer:
                              "dark:bg-input/30 bg-transparent",
                        }}
                     />
                  </div>
                  <div className="grid gap-3">
                     <Label htmlFor="sheet-demo-username">Description</Label>
                     <Textarea
                        id="sheet-demo-username"
                        className="resize-none"
                        defaultValue=""
                     />
                  </div>
                  <div className="grid gap-3">
                     <Label htmlFor="sheet-demo-username">Slug</Label>
                     <Input id="sheet-demo-username" defaultValue="" />
                  </div>
               </div>
               <SheetFooter>
                  <Button type="submit">Save changes</Button>
                  <SheetClose asChild>
                     <Button variant="outline">Close</Button>
                  </SheetClose>
               </SheetFooter>
            </SheetContent>
         </Sheet>
      </div>
   );
}
